[project]
name = "p1"
version = "0.1.0"
description = "Smellpanty"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "rich>=13.9.2",
]

[project.scripts]
p1 = "p1:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
